#!/usr/bin/env python
# coding: utf-8

# In[1]:


fa_en_dict = {
    "سلام": "hello",
    "خداحافظ": "goodbye",
    "لطفاً": "please",
    "ممنون": "thank you",
    "بله": "yes",
    "نه": "no",
    "چی": "what",
    "کی": "when",
    "کجا": "where",
    "چرا": "why",
    "چطور": "how",
    "دوست": "friend",
    "خانه": "home",
    "مدرسه": "school",
    "کتاب": "book",
    "غذا": "food",
    "آب": "water",
    "کار": "work",
    "ماشین": "car",
    "پول": "money",
    "خانواده": "family",
    "معلم": "teacher",
    "دانش‌آموز": "student",
    "صبح": "morning",
    "شب": "night",
    "امروز": "today",
    "فردا": "tomorrow",
    "دیروز": "yesterday",
    "ساعت": "hour",
    "دقیقه": "minute",
    "ثانیه": "second",
    "سال": "year",
    "ماه": "month",
    "هفته": "week",
    "روز": "day",
    "آسمان": "sky",
    "خورشید": "sun",
    "ماه": "moon",
    "زمین": "earth",
    "باران": "rain",
    "برف": "snow",
    "باد": "wind",
    "دریا": "sea",
    "کوه": "mountain",
    "جنگل": "forest",
    "رودخانه": "river",
    "بیابان": "desert",
    "جزیره": "island",
    "کسی": "someone",
    "هیچکس": "no one",
    "همه": "everyone",
    "جایگاه": "place",
    "شهر": "city",
    "روستا": "village",
    "کشور": "country",
    "دولت": "government",
    "اقتصاد": "economy",
    "سیاست": "politics",
    "خبر": "news",
    "مجله": "magazine",
    "روزنامه": "newspaper",
    "تلویزیون": "television",
    "رادیو": "radio",
    "اینترنت": "internet",
    "وب": "web",
    "تلفن": "phone",
    "کامپیوتر": "computer",
    "لپ‌تاپ": "laptop",
    "تبلت": "tablet",
    "گوشی": "phone",
    "دستگاه": "device",
    "موبایل": "mobile",
    "ایمیل": "email",
    "پیام": "message",
    "نامه": "letter",
    "مدیر": "manager",
    "کارمند": "employee",
    "رئیس": "boss",
    "کارگر": "worker",
    "فروشنده": "salesperson",
    "خریدار": "buyer",
    "مشتری": "customer",
    "بازار": "market",
    "فروشگاه": "store",
    "خرید": "buy",
    "فروش": "sell",
    "پرداخت": "payment",
    "قیمت": "price",
    "هزینه": "cost",
    "مبلغ": "amount",
    "درآمد": "income",
    "سرمایه": "investment",
    "سود": "profit",
    "ضرر": "loss",
    "بیمه": "insurance",
    "بانک": "bank",
    "حساب": "account",
    "پول": "money",
    "دلار": "dollar",
    "یورو": "euro",
    "ریال": "rial",
    "املاک": "property",
    "زمین": "land",
    "خانه": "house",
    "آپارتمان": "apartment",
    "اتاق": "room",
    "پاساژ": "mall",
    "ساختمان": "building",
    "اجاره": "rent",
    "خرید": "buy",
    "فروش": "sell",
    "ساخت": "construction",
    "تعمیر": "repair",
    "پیمانکار": "contractor",
    "معمار": "architect",
    "مهندس": "engineer",
    "الکتریسیته": "electricity",
    "آب": "water",
    "گاز": "gas",
    "گرمایش": "heating",
    "سرمایش": "cooling",
    "تهویه": "ventilation",
    "میز": "table",
    "صندلی": "chair",
    "سقف": "ceiling",
    "دیوار": "wall",
    "پنجره": "window",
    "در": "door",
    "کف": "floor",
    "چراغ": "light",
    "لامپ": "lamp",
    "دستگیره": "handle",
    "پرده": "curtain",
    "کمد": "closet",
    "شلف": "shelf",
    "تلویزیون": "television",
    "رادیو": "radio",
    "دستگاه": "device",
    "تلفن": "phone",
    "گوشی": "mobile",
    "کامپیوتر": "computer",
    "لپ‌تاپ": "laptop",
    "تبلت": "tablet",
    "دستگاه": "device",
    "سیم‌کارت": "SIM card",
    "پاسپورت": "passport",
    "کارت ملی": "ID card",
    "گواهینامه": "driver's license",
    "مدرک": "certificate",
    "تحصیلات": "education",
    "آموزش": "training",
    "دوره": "course",
    "کلاس": "class",
    "کتاب": "book",
    "مقاله": "article",
    "جزوه": "notes",
    "تحقیق": "research",
    "پایان‌نامه": "thesis",
    "پروژه": "project",
    "استاد": "professor",
    "دانشجو": "student",
    "آزمون": "exam",
    "امتحان": "test",
    "پاس": "pass",
    "شکست": "fail",
    "قبول": "accept",
    "رد": "reject",
    "نمره": "grade",
    "مدرک": "degree",
    "کارشناسی": "bachelor",
    "کارشناسی ارشد": "master's",
    "دکتری": "PhD",
    "کتابخانه": "library",
    "درباره": "about",
    "مقصد": "destination",
    "مسیر": "path",
    "سفر": "travel",
    "رزرو": "reservation",
    "بلیط": "ticket",
    "هواپیما": "plane",
    "قطار": "train",
    "اتوبوس": "bus",
    "ماشین": "car",
    "دوچرخه": "bicycle",
    "پای پیاده": "on foot",
    "فرودگاه": "airport",
    "ایستگاه": "station",
    "هتل": "hotel",
    "پاسپورت": "passport",
    "ویزا": "visa",
    "گذرنامه": "passport",
    "مقصد": "destination",
    "موزیک": "music",
    "فیلم": "movie",
    "کتاب": "book",
    "پادکست": "podcast",
    "تلویزیون": "TV",
    "رادیو": "radio",
    "کنسرت": "concert",
    "نماهنگ": "music video",
    "ورزش": "sports",
    "فوتبال": "football",
    "بسکتبال": "basketball",
    "والیبال": "volleyball",
    "تنیس": "tennis",
    "شنا": "swimming",
    "گلف": "golf",
    "وزنه‌برداری": "weightlifting",
    "دویدن": "running",
    "بدنسازی": "bodybuilding",
    "یوگا": "yoga",
    "رقص": "dance",
    "ورزشکار": "athlete",
    "تیم": "team",
    "مربی": "coach",
    "قهرمان": "champion",
    "بازی": "game",
    "مسابقه": "competition",
    "پیروزی": "victory",
    "شکست": "defeat",
    "حس": "feeling",
    "عشق": "love",
    "دوستی": "friendship",
    "خشم": "anger",
    "غم": "sorrow",
    "شادی": "happiness",
    "غمگینی": "sadness",
    "ترس": "fear",
    "شگفتی": "surprise",
    "دلگرمی": "encouragement",
    "امید": "hope",
    "اعتماد": "trust",
    "صبر": "patience",
    "گناه": "sin",
    "عذاب": "punishment",
    "پشیمانی": "regret",
    "لذت": "pleasure",
    "آرامش": "calm",
    "آزادی": "freedom",
    "امنیت": "security",
    "عزت": "honor",
    "احترام": "respect",
    "شجاعت": "courage",
    "رؤیا": "dream",
    "هدف": "goal",
    "امکان": "possibility",
    "واقعیت": "reality",
    "چالش": "challenge",
    "راه‌حل": "solution",
    "پاسخ": "answer",
    "سؤال": "question"
}


# In[ ]:


import tkinter as tk

def show_output():
    user_input = entry.get()
    translation = fa_en_dict.get(user_input)
    if translation:
        output = f'''"{user_input}" معادلش میشه: {translation}'''
    else:
        output = f'کلمه "{user_input}" در دیکشنری پیدا نشد!'
    result_label.config(text=output)

root = tk.Tk()
root.title("برنامه مترجم")

label = tk.Label(root, text="یک کلمه فارسی وارد کن:")
label.pack()

entry = tk.Entry(root)
entry.pack()

button = tk.Button(root, text="نمایش خروجی", command=show_output)
button.pack()

result_label = tk.Label(root, text="", fg="blue")
result_label.pack()

root.mainloop()


# In[ ]:





# In[ ]:




